# Generated by Django 3.0.1 on 2020-08-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('auth', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='Students/files')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='Students/cover/')),
            ],
        ),
    ]
