# Generated by Django 3.0.1 on 2020-08-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=150)),
                ('Emp_Code', models.CharField(max_length=5)),
                ('Mobile', models.CharField(max_length=15)),
                ('Position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.Position')),
            ],
        ),
    ]
